name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore: ["keymap-drawer/**"]
jobs:
  build:
    runs-on: ubuntu-latest
    container: zmkfirmware/zmk-build-arm:stable
    steps:
      - uses: actions/checkout@v4
      - run: west init -l config && west update --narrow && west zephyr-export
      - run: west zmk-build -d ./build -q
      - run: mkdir -p firmware && find build -name zmk.uf2 -print0 | xargs -0 -I{} cp --parents {} firmware
      - uses: actions/upload-artifact@v4
        with: {name: firmware, path: firmware}
